---
- hosts: all
  become: yes

  vars:
    mariadb_root_password: "BigSecret2017!"

  tasks:

  - name: Create Icgina gpg file
    copy:
      src: "templates/gpg_content.txt"
      dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-ICINGA"
      owner: "root"
      group: "root"
      mode: 0644

  - name: Ensure Icinga yum repository is present
    yum_repository:
      name: icinga-stable-release
      description: "ICINGA (stable release for epel)"
      baseurl: "http://packages.icinga.com/epel/$releasever/release/"
      enabled: yes
      gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ICINGA"
      gpgcheck: yes

  - name: Install epel
    yum:
      name: epel-release
      state: present

  - name: Install Icinga
    yum:
      name: "{{ item }}"
      state: "present"
    with_items:
      - icinga2
      - icinga2-selinux
      - vim-icinga2

  - name: Install MariaDB for Icinga Web
    yum:
      name: "{{ item }}"
      state: "present"
    with_items:
      - mariadb-server
      - mariadb
      - MySQL-python
      - icinga2-ido-mysql

  - name: Ensure MariaDB is started
    service:
      name: mariadb
      state: started
      enabled: yes

  # https://github.com/PCextreme/ansible-role-mariadb/blob/master/tasks/mysql_secure_installation.yml
  - name: Set root Password
    mysql_user: name=root host={{ item }} password={{ mariadb_root_password }} state=present
    with_items:
      - 127.0.0.1
      - ::1
      - icinga
      - localhost

  - name: Add .my.cnf
    template: src=templates/my.cnf.j2 dest="{{ item.file }}" owner="{{ item.owner }}" group="{{ item.group }}" mode=0600
    with_items:
      - { "file": "/root/.my.cnf", "owner": "root", "group": "root" }
      - { "file": "/home/vagrant/.my.cnf", "owner": "vagrant", "group": "vagrant" }

  - name: Remove anonymous users
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DELETE FROM mysql.user WHERE User=''
    changed_when: False

  - name: Disallow root login remotely
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
    changed_when: False

  - name: Remove test database and access to it
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DROP DATABASE test
      - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
    changed_when: False
    ignore_errors: True

  - name: Reload privilege tables
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - FLUSH PRIVILEGES
    changed_when: False

  - name: Ensure icinga2 service is started
    service:
      name: icinga2
      state: started
      enabled: yes

  - name: Install nagios-plugins packages
    yum:
      name: "nagios-plugins-all"
      state: "present"
